apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sample-chart.selectorLabels" . | nindent 6 }}
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      name: gitops-pod
      labels:
        {{- include "sample-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: SERVER_PORT
          value: "{{ .Values.service.port }}"
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
      imagePullSecrets: 
        {{- with .Values.imagePullSecrets }}
      - {{ toYaml . }}
        {{- end }}