apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodWIubW9ycGhldXMua3IiOnsidXNlcm5hbWUiOiJsZWVoaDMxMiIsInBhc3N3b3JkIjoiZWFuSHE3ZWZNIiwiZW1haWwiOiJsZWVoaDMxMkB1cmFjbGUuY28ua3IiLCJhdXRoIjoiYkdWbGFHZ3pNVEk2WldGdVNIRTNaV1pOIn19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
