apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-chart.fullname" . }}
  labels:
    {{- include "sample-chart.selectorLabels" . | nindent 6 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
